lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  alias StorexWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Cart
    plug Plugs.ItemsCount
    plug Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack


    get "/", VideoController, :index
    get "/purchased", VideoController, :purchased
    resources "/videos", VideoController
    get "/watch/:id", WatchController, :show

    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
    resources "/checkout", CheckoutController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex/sales/cart.ex
defmodule Storex.Sales.Cart do
  use Ecto.Schema
  import Ecto.Changeset
  alias Storex.Sales.Cart


  schema "sales_carts" do
    has_many :line_items, Storex.Sales.LineItem
    timestamps()
  end

  @doc false
  def changeset(%Cart{} = cart, attrs) do
    cart
    |> cast(attrs, [])
    |> validate_required([])
  end
end

lib/storex_web/controllers/cart_controller.ex
defmodule StorexWeb.CartController do
  use StorexWeb, :controller
  
  alias StorexWeb.Plugs
  alias Storex.Sales
  alias Storex.Media.Store

  def show(conn, _params) do
    cart = Plugs.Cart.get(conn)
    items = Sales.list_line_items(cart)
    total = Sales.line_items_total_price(items)
    render conn, "show.html", items: items, total: total
  end

  def create(conn, %{"video_id" => video_id}) do
    cart = Plugs.Cart.get(conn)
    video = Store.get_video(video_id)
    Sales.add_video_to_cart(video, cart)

    redirect(conn, to: cart_path(conn, :show))
  end

  def delete(conn, %{"video_id" => video_id}) do
    cart = Plugs.Cart.get(conn)
    video = Store.get_video(video_id)
    Sales.remove_video_from_cart(video, cart)

    redirect(conn, to: cart_path(conn, :show))
  end
end

lib/storex_web/views/cart_view.ex
defmodule StorexWeb.CartView do
  use StorexWeb, :view

  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/templates/cart/show.html.eex
<h1>Your cart</h1>

<ul class="cart-items">
  <%= for item <- @items do %>
    <li class="cart-item">
    <div class="cart-item__image ">
      <video width="80vw" height= "80vh " controlsList="nodownload">
          <source src=<%= item.video.s3_url %> type="video/mp4">
        </video>
        </div>

         <div class="cart-item__title">
                <span><%= item.video.title %></span>
              </div>

      <div class="cart-item__units">
        <div class="value-tag" style="float: right">
          <h2 class="value-tag__title" >days</h2>
          <span class="value-tag__content">
            <div class="step minus">
              <%= link "-", to: cart_path(@conn, :delete, video_id: item.video_id), method: :delete %>
            </div>
            <%= item.quantity %>
            <div class="step plus">
              <%= link "+", to: cart_path(@conn, :create, video_id: item.video_id), method: :create %>
            </div>
          </span>
        </div>
      </div>
      <div class="cart-item__price">
        <div class="value-tag">
          <h2 class="value-tag__title">price</h2>
          <span class="value-tag__content">
            <%= format_price(item.video.price) %>
          </span>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<div class="value-tag-total">
  <h2 class="value-tag__title" >total</h2>
  <span class="value-tag__content"><%= format_price(@total) %></span>
</div>

<%= link "Checkout", to: checkout_path(@conn, :new), class: "button button-primary" %>