lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  alias StorexWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Plugs.Cart
    plug Plugs.ItemsCount
    plug Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack


    get "/", VideoController, :index
    get "/purchased", VideoController, :purchased
    resources "/videos", VideoController
    get "/watch/:id", WatchController, :show

    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
    resources "/checkout", CheckoutController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex/media/video.ex
defmodule Storex.Media.Video do
  use Ecto.Schema
  use Rummage.Ecto
  import Ecto.Changeset
  alias Storex.Media.Video

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  @derive {Phoenix.Param, key: :id}

  schema "videos" do
    field :content_type, :string
    field :filename, :string
    field :path, :string
    field :title, :string
    field :video_file, :any, virtual: true
    field :description, :string
    field :price, :decimal
    field :s3_url, :string

    timestamps()
  end

  def put_video_file(changeset) do
    case changeset do
    %Ecto.Changeset{valid?: true, changes: %{video_file: video_file}} ->
      path = Ecto.UUID.generate() <> Path.extname(video_file.filename)
      changeset
      |> put_change(:path, path)
      |> put_change(:filename, video_file.filename)
      |> put_change(:content_type, video_file.content_type)
    _ ->
      changeset
  end
 end
  @doc false
  def changeset(%Video{} = video, attrs) do
    video
    |> cast(attrs, [:title, :filename, :content_type, :path, :video_file, :description, :price, :s3_url])
    |> validate_required([:title, :video_file, :description, :price])
    |> put_video_file()
  end
end

lib/storex_web/controllers/video_controller.ex
defmodule StorexWeb.VideoController do
  use StorexWeb, :controller
  use Rummage.Phoenix.Controller

  import Storex.Util, only: [build_video_path: 1]
  alias Storex.Media
  alias Storex.Media.Video
  alias Storex.Repo

  plug StorexWeb.Plugs.AdminOnly when action not in [:index, :show, :purchased]


  def index(conn, params) do
    videos = Media.list_videos()

    {query, rummage} = Video
    |> Video.rummage(params["rummage"])

    videos = Repo.all(query)

    render(conn, "index.html", videos: videos, rummage: rummage)
  end

  def purchased(conn, _params) do
    videos = Media.show_purchased(conn.assigns.current_user.id)
    render(conn, "purchased.html", videos: videos)
  end

  def new(conn, _params) do
    changeset = Media.change_video(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" =>  video_params} ) do
    file_uuid = UUID.uuid4(:hex)
    video_filename = video_params["video_file"].filename
    unique_filename = "#{file_uuid}.#{video_filename}"

    {:ok, video_binary} = File.read(video_params["video_file"].path)
    bucket_name = System.get_env("BUCKET_NAME")
    video =
      ExAws.S3.put_object(bucket_name, unique_filename, video_binary)
      |> ExAws.request!
    # build the video url and add to the params to be stored
    updated_params =
#      put_in(video_params["video_file"].path, "https://#{bucket_name}.s3.amazonaws.com/#{bucket_name}/#{unique_filename}")
      Map.put(video_params, "s3_url",  "https://#{bucket_name}.s3.amazonaws.com/#{bucket_name}/#{unique_filename}")

    changeset = Video.changeset(%Video{}, updated_params)
    require IEx; IEx.pry
    case Repo.insert(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video uploaded successfully!")
        |> redirect(to: video_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
#    case Media.create_video(updated_params) do
#      {:ok, test} ->
#        persist_file(video, video_params["video_file"])
#
#
#        conn
#        |> put_flash(:info, "Video created successfully.")
#        |> redirect(to: video_path(conn, :show, video))
#      {:error, %Ecto.Changeset{} = changeset} ->
#        render(conn, "new.html", changeset: changeset)
#    end
  end

  defp persist_file(video, %{path: temp_path}) do
    video_path = build_video_path(video)
    unless File.exists?(video_path) do
      video_path |> Path.dirname() |> File.mkdir_p()
      File.copy!(temp_path, video_path)
    end
  end

  def show(conn, %{"id" => id}) do
    video = Media.get_video!(id)
    render(conn, "show.html", video: video)
  end

  def edit(conn, %{"id" => id}) do
    video = Media.get_video!(id)
    changeset = Media.change_video(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}) do
    video = Media.get_video!(id)

    case Media.update_video(video, video_params) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    video = Media.get_video!(id)
    {:ok, _video} = Media.delete_video(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: video_path(conn, :index))
  end
end

lib/storex_web/views/video_view.ex
defmodule StorexWeb.VideoView do
  use StorexWeb, :view
  use Rummage.Phoenix.View

  import StorexWeb.Helpers.PriceFormatter
end

lib/storex_web/templates/video/edit.html.eex
<h2>Edit Video</h2>

<%= render "form.html", Map.put(assigns, :action, video_path(@conn, :update, @video)) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/storex_web/templates/video/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

      <div class="form-field">
        <%= label f, :price %>
        <%= error_tag f, :price %>
        <%= text_input f, :price %>
      </div>

      <div class="form-field">
        <%= label f, :description %>
        <%= error_tag f, :description %>
        <%= textarea f, :description %>
      </div>

    </div>

  <div class="form-group">
      <%= label f, :video_file, "Video", class: "control-label" %>
      <%= file_input f, :video_file, required: true, class: "form-control" %>
      <%= error_tag f, :video_file %>
    </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/storex_web/templates/video/index.html.eex
 <%= if @is_admin do %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Filename</th>
      <th>Content type</th>
      <th>Path</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.title %></td>
      <td><%= video.filename %></td>
      <td><%= video.content_type %></td>
      <td><%= video.path %></td>

      <td class="text-right">
        <span><%= link "Show", to: video_path(@conn, :show, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: video_path(@conn, :edit, video), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
  <% end %>

<div>

<div style="text-align: ">
<%= search_form(@conn, @rummage, [fields:
    [
        title: %{label: "", search_type: "ilike"},
    ], button_class: "btn hidden",
]) %>

</div>



<section class="video-list">
  <ul class="grid">
    <%= for video <- @videos do %>
      <li class="grid-item">
        <div class="video video-small">
          <%= link to: video_path(@conn, :show, video.id) do %>
            <video class="preview" width="200" height="200"  controlsList="nodownload" muted webkitallowfullscreen mozallowfullscreen allowfullscreen poster="">
                            <source src=<%= video.s3_url %> type="video/mp4">
                        </video>
            <h3 class="video__title"><%= video.title %></h3>
          <% end %>
          <span class="video__price"><%= format_price(video.price) %></span>
        </div>
      </li>
    <% end %>
  </ul>
</section>

lib/storex_web/templates/video/new.html.eex
<h2>New Video</h2>

<%= render "form.html", Map.put(assigns, :action, video_path(@conn, :create)) %>

<span><%= link "Back", to: video_path(@conn, :index) %></span>

lib/storex_web/templates/video/purchased.html.eex
<section class="video-list">
  <ul class="grid">
    <%= for video <- Enum.map(@videos, fn {video, order, time} -> {video, order, time} end) do %>
      <li class="grid-item">
        <div class="video video-small">
         <p class="video__title rental_time"><%= NaiveDateTime.to_string(NaiveDateTime.add(elem(video, 1), elem(video, 2) * 86400, :seconds)) <> " UTC" %></p>
          <%= link to: watch_path(@conn, :show, elem(video, 0).id) do %>
            <video class="preview" width="90%" height="90%"  controlsList="nodownload" muted webkitallowfullscreen mozallowfullscreen allowfullscreen poster="">
                <source src=<%= elem(video, 0).s3_url %> type="video/mp4">
            </video>
            <h3 class="video__title"><%= elem(video, 0).title %></h3>

          <% end %>
        </div>
      </li>
    <% end %>
  </ul>




</section>

lib/storex_web/templates/video/show.html.eex
<h1><%= @video.title %></h1>

<div class="video">
  <video width="200" height="200" controlsList="nodownload">
    <source src=<%= @video.s3_url %>#t=0.1" type="video/mp4">
  </video>

  <p class="video__description">
    <%= @video.description %>
  </p>
</div>

<div class="value-tag" >
  <h2 class="value-tag__title">price</h2>
  <span class="value-tag__content"><%= format_price(@video.price) %></span>
</div>


<%= link "Add to cart", to: cart_path(@conn, :create, video_id: @video.id), method: :create, class: "button button-primary" %>

<%= if @is_admin do %>
  <%= link "Edit", to: video_path(@conn, :edit, @video), class: "button" %>
  <%= link "Delete", to: video_path(@conn, :delete, @video), method: :delete, data: [confirm: "Are you sure?"], class: "button button-danger" %>
<% end %>